### PR TITLE
V0.2.0

### PR DESCRIPTION
**Pull request by arobson**
* Add logging support via whistlepunk
 * Add logging statements to assist with troubleshooting/debugging
 * #24 - Connection should not close until after all queues have completed batch processing (only applies to user initiated connection shutdown)
 * #30 - Escape passwords to be connection URI safe
 * #17, #19 - Unhandled messages
  * Nack unhandled messages by default
  * Provide configurable strategies for handling unhandled messages
 * #26 - Support custom reply queue definitions per connection
 * Add behavioral specs to improve coverage and testing story
 * Fix bug in `reject` batching implementation
 * Refactor of exchange and queue implementation into channel behavior and FSM
 * Reject exchange and queue creation promises on failure
 * Reject publish and subscribe calls on failed exchanges and queues

### CODE REVIEW

**Comment by rogueneiner** [comment]
I see what you've done, @arobson - don't think you will escape my wrath if you can't learn to submit reasonably sized PRs.

atomic_rogue

**Comment by dcneiner** [comment]
@arobson @rogueneiner Oh. Wow.

**Comment by derickbailey** [comment]
is the v0.2.0 release the right one to use? or v0.2.0-8?

i'm looking forward to getting these changes - lots of stuff in here that will help. just want to make sure i use the right version, and i'm not sure which version that would be since github shows -8 as the most recent tag / release

**Comment by arobson** [comment]
@derickbailey - sorry about the confusion there, I wish github would let you pick how to sort tags. In semver style, the dash # indicates a prerelease. 0.2.0 is what you want from NPM and has the new features/fixes designed to address some of the issues you've run into.

**Comment by derickbailey** [comment]
ok, cool. thought it was that (semver and all) just wanted to make sure :)

**Comment by ifandelse** [comment]
WOW - @rogueneiner!

**Pull request merged**
