### PR TITLE
Enhancements & Bug fixes

### PR DESCRIPTION
**Pull request by arobson**
* #91 - Provide publish timeout
 * #98 - No-op duplicate exchange, queue and binding declarations
 * #96 - Fall back to routing key if no type is provided for routing
 * #94 - Update amqplib dependnecy to 0.4.0 to support Node 4
 * #77 - Add explanation of connection events
 * #95 - Add test coverage for wildcards in handle
 * Change log namespaces to use '.' delimiter instead of ':'

### CODE REVIEW

**Comment by arobson** [comment]
@derickbailey - this PR should fix the issue you saw. It should also prevent multiple configure calls from running amok.

**Comment by derickbailey** [comment]
awesome! will give this a whirl later today, hopefully. might be tomorrow, though.

**Comment by derickbailey** [comment]
initial test of my demo code looks good. i ran 50K messages, bumping memory up to 2GB+, then ran 100 messages every 20 seconds for a little bit, and memory dropped back to 180K! 

going to run this through my real system now to make sure it all works still.

**Comment by derickbailey** [comment]
load testing on my primary system looks good! memory use jumps and drops as expected, and the full system is running smoothly with all these updates. 

thanks @arobson! :)

**Comment by derickbailey** [comment]
is there an ETA on this being merged and released? I have a deploy window of Thursday, the 5th... not a huge deal if i have to run from your branch for now, though.

**Comment by dermidgen** [comment]
@derickbailey - thought I was going crazy; and here's there already a PR and a fix.
I will do some testing here as well.  @derickbailey - roughly how large are the messages you're testing?
Thanks!!! @arobson

**Comment by derickbailey** [comment]
@dermidgen i have a sample of one of my messages here in the gist linked from #98 - honestly, though, this is a small sample json file. my production system has some messages that are 10x this size, easily. i would prefer to not have such large messages... but it is what it is, right now.

**Comment by benjsicam** [comment]
Hope this would get merged soon. :)

**Comment by joshrivers** [comment]
Any help needed to get this merged to trunk?

**Comment by derickbailey** [comment]
#highfives thanks @arobson :)

**Comment by joshrivers** [comment]
+1 Thanks!

**Pull request merged**
