### PR TITLE
Add vagrant support for virtualbox provider

### PR DESCRIPTION
**Pull request by josephfrazier**

### CODE REVIEW

**Comment by derickbailey** [comment]
any chance of getting this to work with Parallels, as well? I'm unfamiliar with vagrant, but I have the Parallels plugin for it... i just don't know how to get it working :)

**Comment by arobson** [comment]
@joseph-onsip rather than change this and remove the url (which is helpful for anyone who doesn't have that image already), it'd be nice to have Vagrant.{provider} sample files and then update the README. I can try to find docs for Parallels support, but I won't be able to test for that specifically.

**Comment by derickbailey** [comment]
if there's something i can do to help test the parallels configuration, let me know. i run parallels as my VM setup for my dev environment, and i want to be able to run / test wascally on my box. 

i do know you have to install the vagrant provider: https://github.com/Parallels/vagrant-parallels - and i've done that. i just don't know what kind of VM i need to stand up, with what configuration (OS, software installation, etc)

**Comment by joseph-onsip** [comment]
Thanks for the feedback @arobson. I removed the `box_url` since it was tied to the `vmware_fusion` provider, and [Vagrant doesn't allow per-provider `box_url` values](https://github.com/mitchellh/vagrant/issues/1438). Now, that box name resolves to [the one in the public catalog](https://atlas.hashicorp.com/phusion/boxes/ubuntu-14.04-amd64), and the proper `.box` file (for the specified provider) is automatically downloaded and imported if the user doesn't already have it. For example:

```
vagrant version && vagrant up
Installed Version: 1.7.4
Latest Version: 1.7.4

You're running an up-to-date version of Vagrant!
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'phusion/ubuntu-14.04-amd64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'phusion/ubuntu-14.04-amd64'
    default: URL: https://atlas.hashicorp.com/phusion/ubuntu-14.04-amd64
==> default: Adding box 'phusion/ubuntu-14.04-amd64' (v2014.04.30) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/phusion/boxes/ubuntu-14.04-amd64/versions/2014.04.30/providers/virtualbox.box
==> default: Successfully added box 'phusion/ubuntu-14.04-amd64' (v2014.04.30) for 'virtualbox'!
```

We could have multiple Vagrantfile templates instead, but then there would be duplication between them.

**Comment by joseph-onsip** [comment]
@arobson, it turns out that we *can* override the virtualbox provider's `box_url` after all (see 8cd687c25a8b876aba524c11e48ce200d37db983). Now, the Vagrantfile.sample changes consist only of a new provider section, without modifying the original vmware_fusion functionality.

@derickbailey, I don't use parallels, so I'm going to keep my changes focused on virtualbox, but you could probably take a similar approach in your Vagrantfile, adding a section that overrides the `box_url` with one that works for parallels. See https://parallels.github.io/vagrant-parallels/

**Comment by dermidgen** [comment]
@joseph-onsip  Thank you for this.

@arobson I haven't been able to run under vmware-fusion and I've been testing against rabbit in a docker container instead. Can you verify that when you get the same behavior from a virtualbox provider? I see a lot of tests that aren't passing and I do see different behavior vs pointing at a docker container.

**Comment by joseph-onsip** [comment]
Glad you find it useful, @dermidgen.

A potential alternative to defining multiple providers might be to just use the [Docker provider](https://docs.vagrantup.com/v2/docker/), since the provisioning is done almost entirely via Docker anyway, and Vagrant comes with Docker support out of the box

**Comment by arobson** [comment]
@josephfrazier thank you for all the time you put into this issue! Sorry it's taken me so long to get around to merging this one in.

**Pull request merged**
